author: Steven Hicks
title: 'Collaborating Effectively Through Pull Requests'
description: 'Slides for Collaborating Effectively Through Pull Requests, a presentation by Steven Hicks'
output: build/index.html
theme: steve
themeSet: src/theme.css
url: https://pull-requests.stevenhicks.me
# ogImage:
bespoke:
  # vvv turn off the on-screen controller (but P will still open presenter mode)
  osc: false
